[package]
name = "rust_metal_gemm"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_metal_gemm"
crate-type = ["staticlib", "cdylib"]

[dependencies]
metal = "0.25.0"
objc = "0.2.7"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1